version: '3.8'

networks:
  backend:
    external: true
services:


  # FastAPI application (build the image)
  cardano-autonomous:
    build: .  # Path to your FastAPI project directory
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://root:root@postgres:5432/cardano_autonomous_agent_testing_db
      - KAFKA_BROKERS=kafka:9093
    networks:
      - backend

