name: Backend Service Docker Image Builder

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build_on_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: backend:latest
          context: autonomous_agent_api
