name: Docker Build and Deploy

on:
  push:
    branches:
      - master
      - dev
      - test
    tags:
      - "*"

jobs:
  build_on_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - agent-manager
          - api
          - agent-node
          - frontend
          - dbsync-api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Wait for 1 minute
        run: sleep 1m

  deploy_services:
    needs: build_on_push
    strategy:
      matrix:
        service:
          - agent-manager
          - api
          - frontend
          - dbsync-api
      max-parallel: 1

    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: ${{ matrix.service }}
      GITHUB_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Wait for 1 minute
        run: sleep 1m

